EADME
â€”ÍŸÍŸÍÍğ‚ğ˜ğğ„ğ‘ â˜¢ï¸_ğ–£˜ -ğğğ“ âš ï¸ ğ‘»ğ‘¬ğ‘¨ğ‘´_ â˜¢ï¸
â– A Massanger  Multi Device Bot To Take Your Massanger To Another Level ! â–

CLICK HERE IF YOU ARE NEW TO BOTS




Followers Stars Forks Size   



â€”ÍŸÍŸÍÍğ‚ğ˜ğğ„ğ‘ â˜¢ï¸_ğ–£˜ -ğğğ“ âš ï¸ ğ‘»ğ‘¬ğ‘¨ğ‘´_ â˜¢ï¸
68747470733a2f2f692e696d6775722e636f6d2f4c7948696333692e676966
 
68747470733a2f2f692e696d6775722e636f6d2f4c7948696333692e676966


â– DEPLOY_WORKFLOWS â–
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Step to check out the repository code
    - uses: actions/checkout@v2

    # Step to set up the specified Node.js version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # Step to install dependencies
    - name: Install dependencies
      run: npm install

    # Step to run the bot with the correct port
    - name: Start the bot
      env:
        PORT: 8080
      run: npm start
